### ISSUE TITLE
Logging middleware should not be always-applied and better move to separate crate

### ISSUE THREAD

**Issue by iyuq** [rustasync/tide#107]
Logging to console significantly affect the QPS of the framework. With the logging middleware, the QPS of the simple `hello-world` example drops from 
```
Running 10s test @ http://localhost:8000
  4 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.06ms    1.69ms  32.84ms   92.69%
    Req/Sec     2.63k   472.73     4.72k    81.59%
  105226 requests in 10.10s, 13.05MB read
Requests/sec:  10416.80
Transfer/sec:      1.29MB
```
to 
```
Running 10s test @ http://localhost:8000
  4 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.93ms    2.38ms  33.97ms   88.50%
    Req/Sec     1.36k   287.61     2.21k    74.75%
  54088 requests in 10.02s, 6.71MB read
Requests/sec:   5399.07
Transfer/sec:    685.43KB
```
I think we should give user the choice to choose whether or not use logging middleware.
To solve this, I think we can offer the choice by add a new constructor for app.
like
```
pub fn new(data: Data) -> App<Data> {
        let app = App {
            data,
            router: Router::new(),
            default_handler: BoxedEndpoint::new(async || http::status::StatusCode::NOT_FOUND),
        };
        app
}

pub fn default(data: Data) -> App<Data> {
        let logger = RootLogger::new();
        let mut app = App {
            data,
            router: Router::new(),
            default_handler: BoxedEndpoint::new(async || http::status::StatusCode::NOT_FOUND),
        };

        // Add RootLogger as a default middleware
        app.middleware(logger);
        app
}
```

Furthermore, I think it's better to separate the Logging middleware from the core framework, for example, we could move the `tide` to the `tide-core` crate to `tide` workspace, add a `tide-logging` crate for `tide` crate. Like the tree graph below:
```
tide
|-tide-core
|--Cargo.toml
|-tide-logging
|--Cargo.toml
|-Cargo.toml
```

**Comment by bIgBV** [comment]
The current state of logging is just a starting point to integrate logging into tide, there's a lot of discussion regarding this over at #8  and nothing is concrete yet. I like the idea of separating logging out into it's own crate in the workspace though. Please add your thoughts over at the other discussion as well :)
