### ISSUE TITLE
Consider using route_recognizer instead of path-table

### ISSUE THREAD

**Issue by tirr-c** [rustasync/tide#141]
## Detailed Description
For now `Router` is using `path-table` for its route matching. Consider changing the algorithm by replacing it with [`route_recognizer`].

The published version of `route_recognizer` is unmaintained for about 2 years, and seems to have reversed precedence of path segment matching (conduit-rust/route-recognizer.rs#21). Maybe we can fork the repository and apply some patches.

[`route_recognizer`]: https://github.com/conduit-rust/route-recognizer.rs

## Context
Related to #12. `route_recognizer` seems to have more sophiscated route matching algorithm than `path-table`. I expect it to fix most of the counterintuitive cases.

**Comment by krircc** [comment]
There is [actix_router](https://github.com/actix/actix-net/tree/master/router), but it is Independent，and dont dependent Actix* . It is General

**Comment by aturon** [comment]
Note: this is the algorithm ultimately used by crates.io:

- https://github.com/conduit-rust/conduit-router
- https://github.com/rust-lang/crates.io/blob/master/Cargo.toml#L76

so it's "maintained", just hasn't needed a lot of updating. Definitely a worthy candidate to look at, and I  expect the current owners would be  interested in moving it into the rust-net-web org.

**Comment by bIgBV** [comment]
One thing to consider for the router API is a way of providing reverse lookups #24. I'll go into more detail about the small survey I did of current implementation of such an API in django and flask, but both of them leverage the router to provide a reverse lookups of endpoints to paths for building URLs.

**Comment by tirr-c** [comment]
So, we need a router that:
* has intuitive path matching algorithm
* can be nested
* has ability to perform reverse lookups

`path-table` currently used by Tide addresses only the second point, and both `route_recognizer` and `actix-router` don't have reverse lookup feature (as far as I understand). I think we need to fork and add needed functionality anyway, so how about experimenting with `route_recognizer`? It might be challenging with state machines, though.

**Comment by fundon** [comment]
I wrote a https://github.com/trek-rs/path-tree.

* supports reverse lookups

* supports `named` and `catch-all` likes https://github.com/julienschmidt/httprouter, but more flexible.

Currently, I am thinking about how to generate urls. Maybe the `{}` is best syntax.

**Comment by aturon** [comment]
The #156 PR moved to route-recognizer. And in general it should now be much easier to swap out the underlying router. I'm open to moving to path-tree if that seems like a better option -- though offhand the two seem pretty comparable in terms of functionality (and route-recognizer is used by crates.io, so there's *some* impetus for sharing).

I'm going to close this for now, but if @fundon or others want to explore moving from route-recognizer to path-tree or something else, please feel free to open a new issue and make a case there!
