### ISSUE TITLE
Extract named query parameter

### ISSUE THREAD

**Issue by niklasf** [rustasync/tide#147]
## Feature Request

Extract named parameters from query strings (`?param1=foo&param2=bar`). 

### Detailed Description

tide supports query extraction (#14) using `UrlQuery`. For example:

```rust
async fn hello_world(UrlQuery(q): UrlQuery<String>) -> String {
    q // "param1=foo&param2=bar" (how to extract the value of param1?)
}
```

`UrlQuery<T>` parses `T` using `FromStr`, but if we want to parse the query and extract individual parameters we're on our own.

### Context

Working with query parameters is common in all kinds of applications.

### Possible Implementation

Looking at tide itself, it could be implemented similarly to named segments. Alternatives from other frameworks:

* Rocket: Derivable [`FromForm`](https://api.rocket.rs/v0.4/rocket/request/trait.FromForm.html) trait. Function parameter is marked as query string in route declaration.
  ```rust
  #[get("/hello?<q>")]
  fn hello_world(q: &MyTypeThatImplsFromForm) -> /* ... */
  ```
* actix-web: Parameter [`Query<T: Deserialize>`](https://docs.rs/actix-web/0.7.18/actix_web/struct.Query.html) newtype using [serde_urlencoded](https://crates.io/crates/serde_urlencoded).
* tower-web: Derivable [`Extract`](https://docs.rs/tower-web/0.3.5/tower_web/extract/trait.Extract.html) trait. Function parameter must be named `query_string`.
 ```rust
 #[get("/query-string")]
 fn hello_world(&self, query_string: Option<Foo>) -> /* ... */
  ```

The actix-web approach might be best for Tide, because no macro magic is involved. (Well ... except that in Serde).

**Comment by yoshuawuyts** [comment]
Related: https://github.com/rustasync/tide/issues/108

**Comment by aturon** [comment]
This should be easier to explore now that #156 has landed!

**Comment by secretfader** [comment]
#175 is an updated version of this PR.
