### ISSUE TITLE
Find a way to configure the response headers 

### ISSUE THREAD

**Issue by gruberb** [rustasync/tide#154]
## Feature Request
Right now we hardcode the `header` in the [`impl IntoResponse for ...` ](https://github.com/rustasync/tide/blob/master/src/response.rs#L59). If we want to return different types (`text/html` instead of `text/plain` for example to serve templates), we would need to be able to configure the header before we send the response.

## Detailed Description
1. We could expose the `http::Response::builder()`
2. We could use macros to set the headers for each route

## Context
I think it is important so we are more flexible in the future and the user can decide which route accepts or sends which headers and status_codes etc.

## Possible Implementation
I don't have a clear idea yet of which route to take. Wanted to bring it up to get input from more experienced people here, but would take the lead of implementing it after a conses is reached.

**Comment by DCjanus** [comment]
Possible implementation could ref this: [IntoResponse::with_statue](https://github.com/rustasync/tide/blob/7e87e4e0699a3fff4453c8a25d3f8f5fa186fdbb/src/response.rs#L22)
