### ISSUE TITLE
Better clarity for configuration API

### ISSUE THREAD

**Issue by prasannavl** [rustasync/tide#158]
_Note: This is mostly just bike-shedding._

The current API has a `ConfigurationBuilder` that `finalize`s, and `Configuration` that `build`s, but really provides `ConfigurationBuilder`. The former is fine, however I feel it lacks parity when combined with the latter.

I think a better approach would be
 - `ConfigurationBuilder::new() -> ConfigurationBuilder`
- `ConfigurationBuilder::build() -> Configuration` (or this could be `finalize` as well - This is fine). 
- `Configutation::from(ConfigurationBuilder)` 

Also: 
- Rename `Configuration::build()` to `Configuration::builder()` as `Configuration::build` intuitively signals building the configuration rather than giving out a builder. 

I see the current one is used this way:
```
let config = Configuration::build().finalize();
```

This changes to one of:
- `ConfigurationBuilder::new().build()`;
- `Configuration::builder().build()` or `Configuration::builder().finalize()`

I'd be happy to submit a PR if this is desirable.

**Comment by yoshuawuyts** [comment]
@prasannavl Thanks for the issue; that's an excellent point! -- we're currently waiting on #156 to progress, but once that's in I think we should definitely take a closer look at our builders.

**Comment by aturon** [comment]
After #156, none of these configuration APIs exist any more :-)
