### ISSUE TITLE
What useful computed properties can we provide?

### ISSUE THREAD

**Issue by aturon** [rustasync/tide#16]
When a value can be lazily computed by request information, it's much nicer to make that value available through [the `Compute` trait](https://github.com/rust-net-web/tide/blob/master/src/request.rs#L12) (and `Computed` extractor) rather than e.g. using middleware or plumbing the `Head` data manually in an endpoint.

What are some examples of such values? One might be: a parsed version of the query segment. Let's generate a bunch of ideas and then implement them!

**Comment by pickfire** [comment]
Maybe we can pre-compute the `ETag` and `Last-Modified`? This might be a usecase for some API but I have yet seen some interesting implementation for this.

**Comment by tzilist** [comment]
Another one might be a passport type thing to handle different types of authentication? This may not be something worth providing out of the box from tide but certainly worth showing an example of?

**Comment by tzilist** [comment]
@chrisabruce agreed. I wonder if we can provide scaffolding for something like basic auth, oath, etc. But I think you are right, that should probably be middleware.

**Comment by tzilist** [comment]
We could also provide a set of tools for performing health checks?

**Comment by aturon** [comment]
Closing as of #156, which eliminated the concept of "computed values".
