### ISSUE TITLE
Consider returning multiple responses on a single request

### ISSUE THREAD

**Issue by manifest** [rustasync/tide#165]
HTTP/2 Server Push allows to send multiple responses on a single request. That seems to affect the interface of endpoints.

**Comment by DCjanus** [comment]
I don't think Server Push is "one request, multiple responses", and mostly, it used for static file server like NGINX.

**Comment by secretfader** [comment]
I believe @DCjanus is correct. HTTP/2 Server Push may be useful if you're using Tide as a static file server, but there are other (and at this point, arguably better) tools for the same job.

I can see where it would be helpful

**Comment by secretfader** [comment]
If anything, HTTP/2 Server Push could be useful if Tide is [primarily serving static files](https://jakearchibald.com/2017/h2-push-tougher-than-i-thought/). That said, I bl

**Comment by secretfader** [comment]
If anything, HTTP/2 Server Push could be useful if Tide is [primarily serving static files](https://jakearchibald.com/2017/h2-push-tougher-than-i-thought/). That said, I believe there are other (and at this point, arguably better) tools for the same job.

If we are to implement HTTP/2 Server Push in Tide, perhaps it can begin life as a feature flag, compiled only for compatible HTTP implementations. It feels like there's room for niceties provided by Tide, but the core functionality should live at a lower level.

**Comment by yoshuawuyts** [comment]
@manifest I had the same intuition around that initially too, but after some lengthy discussions with @aturon we concluded that it's actually a pretty natural fit to add HTTP/push and websockets/SSE on top of the streaming request/response model Tide has.

We currently don't have anything around this yet, but I think the interface is in a good spot to allow experimentation around this (:

**Comment by manifest** [comment]
@yoshuawuyts Can I read discussion or description of the streaming request/response model of Tide somewhere?

**Comment by yoshuawuyts** [comment]
@manifest most of it is part of `Request` and `Response` in https://docs.rs/http-service/0.1.4/http_service/, where for Tide possible future extensions could be made by adding methods to `Context` (e.g. for h2 push).

The chats I referenced earlier were in-person, and weren't archived unfortunately. Hopefully this is still useful tho!

**Comment by manifest** [comment]
Ok, thanks. I'll try make sense of it :-)
