### ISSUE TITLE
Used nightly is undocumented

### ISSUE THREAD

**Issue by badboy** [rustasync/tide#173]
tide requires nightly, but this is nowhere documented.
Additionally it's not documented _which_ nightly works.
The one [defined for Travis](https://github.com/rustasync/tide/blame/master/.travis.yml#L3) is old and as shown by Travis, tide doesn't compile anymore.

Please do:
1. Document that it depends on nightly (and why).
2. Document which nightly works, e.g. in a [`rust-toolchain` file](https://github.com/rust-lang/rustup.rs#the-toolchain-file).
3. Use that nightly on CI.

**Comment by badboy** [comment]
Oh, additionally it might be necessary to either have a Cargo.lock committed or version-pin dependencies. I can't get Tide compiled with yesterday's or today's nightly because dependencies fail to build.

**Comment by fairingrey** [comment]
I agree, it should be documented!

By the way, the latest nightly that works with tide currently is `nightly-2019-04-07`, because of https://github.com/rust-lang-nursery/futures-rs/issues/1518. The fix to it was merged just hours ago and futures 0.3.0-alpha.14 is now available with the fix.

However, the `http_service` dependency still relies on 0.3.0-alpha.13, so it can't be used until that's also updated, I think...

**Comment by DCjanus** [comment]
Not related to the lock file, more is the change of the standard library.
As library, tide should not lock dependencies, patch version change should not break user.

**Comment by badboy** [comment]
@fairingrey cool, thanks!
@DCjanus Normally I would agree, but this being all unstable and nightly APIs there's a higher chance on breaking.

**Comment by secretfader** [comment]
We mention that Tide requires the `async_await` feature flag in the README. As someone familiar with the Rust ecosystem, this is obvious enough. I could see where newcomers might be tripped up.

I'm conflicted over whether we need a notice that Tide requires nightly (and a fairly recent one, too). If this question were posed a few months ago, I'd suggest notifying potential users. However, according to my understanding, we're only a few months away, maximum, from having a stable implementation of Futures in the standard library.

Tide isn't ready for prime-time just yet. As of now, I favor waiting out the release of `std::future` and updating the README when we have news of stability.
