### ISSUE TITLE
Decide on extension trait convention

### ISSUE THREAD

**Issue by aturon** [rustasync/tide#187]
Tide uses many "extension traits" (which extend an existing type with new methods, and have no other impls). We should standardize on a naming convention.

**Comment by aturon** [comment]
One possibility would be `FooExt` where `Foo` is the name of the type being extended -- including the type in the name helps the reader quickly see what is being extended.

A downside is that we want to provide many extensions to `Context`. We'd end up with `cookies::ContextExt` and `forms::ContextExt` etc. But given that you only use these trait names on import, where they will be qualified by module, perhaps this is fine? The paths do contain the full set of relevant info: what is the extension, and what is being extended?

**Comment by bIgBV** [comment]
I think using `ContextExt` would be a good idea. This would be the common type name across the entire ecosystem which would signal that this type extends something on tide's `Context`. I think the recognizability this achieves will be really useful to convey the idea of how it's supposed to be used. Overall it provides a consistent name for the core extension trait in a given crate across all such crates.

@aturon  I agree with you, given that the type itself will only be present at the top of the file for the most part and the type will not be used anywhere else, the import path will give enough context as to where this is coming from.

**Comment by secretfader** [comment]
If I apply this specification to #175, I feel like we have several options:

- `QueryStringExt`
- `UrlQueryExt`
- `QueryExt`

I'm not entirely sure which is appropriate, but the method it defines is `url_query`. So `UrlQueryExt` is probably the most intuitive.

**Comment by fairingrey** [comment]
I'm in support of using the `*Ext` naming scheme -- it's what I see a lot in the ecosystem already and feels the most familiar.

As for the comment above https://github.com/rustasync/tide/issues/187#issuecomment-486456855, yeah I'd also go with `UrlQueryExt`. I think `QueryExt` is a bit too unclear, and `QueryStringExt` doesn't quite feel right (as while it is a string deserialization it doesn't quite describe the entire nature of the extension trait).

**Comment by secretfader** [comment]
@fairingrey Ignore my comment above. I completely misunderstood the convention. A more appropriate naming scheme for the `querystring` module is `tide::querystring::ContextExt`.

**Comment by fairingrey** [comment]
Oh, sorry! Yeah, that makes sense.

**Comment by Nemo157** [comment]
A downside of the chosen convention I recently ran into is not being able to actually bring multiple `ContextExt` into scope. A workaround is to use the relatively recent `use foo::Foo as _;` feature to import the traits _methods_ into scope without having the trait nameable:

```rust
use tide::{cookies::ContextExt as _, forms::ContextExt as _};
```

This can also be mitigated in Tide for prelude users, if Tide has

```rust
pub mod prelude {
    use crate::{cookies::ContextExt as _, forms::ContextExt as _};
}
```

then a user adding `use tide::prelude::*;` will still get the effect of importing the methods without the traits.

**Comment by bIgBV** [comment]
Having a prelude is certainly useful, and I think we eventually should have one for the most common extension traits, but not all of them would be a part of the prelude right.

So we might have to rethink the naming scheme itself.

**Comment by Nemo157** [comment]
Personally I don't mind the `as _`, and am anti-preludes, so I'm happy to keep using that. (Although I've also had to use it in other places to [force importing _crates_](https://github.com/Nemo157/embrio-rs/blob/2afd9648aca3768fbdb5b464358ed7ec69b4fa0f/examples/pca10031/examples/hello.rs#L4-L5) when I don't use any of their items before, so I may be pre-biased).

**Comment by bIgBV** [comment]
But don't you think as the ecosystem grows, the number of such imports would be an annoyance to type always.

Though to be fair, most would only be typed once and then forgotten.

**Comment by yoshuawuyts** [comment]
A few data points:

- [RFC-0445](https://rust-lang.github.io/rfcs/0445-extension-trait-conventions.html#the-convention) defines the general schema of how to name `Ext` traits.
- https://github.com/rustasync/futures-timer/pull/18 recently went through a similar question, and we settled on `FooExt` where `FooExt as _` can be used to prevent conflicts
- In [Runtime's time PR](https://github.com/rustasync/runtime/pull/36/files#diff-b4aea3e418ccdb71239b96952d9cddb6R114) we are defining trait impls that may conflict with `futures::prelude`, but using `as _` in the prelude these problems can be evaded.

Given the prior discussion on this thread also, I feel we should go with the schema laid out in `RFC-0445`, and keep the `as _` use in mind if we ever decide to define a prelude.

**Comment by Nemo157** [comment]
One thing to keep in mind is that _examples_ should use `as _` as well if that's how users are expected to use them (relevant to https://github.com/rustasync/futures-timer/pull/18 as that is currently shadowing `futures::prelude::TryFutureExt` in the example, which could really confuse users as to why their method calls suddenly stop working when introducing `futures-timer`).

**Comment by yoshuawuyts** [comment]
The discussion here has more or less quieted down. The futures crate is now also shadowing extension traits. It feels like we've reached consensus, and it's okay to close this now (:
