### ISSUE TITLE
Document endpoint signatures

### ISSUE THREAD

**Issue by aturon** [rustasync/tide#19]
The `Endpoint` trait documentation should give the key information of *what `Fn` types are actually endpoints*.

**Comment by fairingrey** [comment]
I could work on this issue, it seems fairly simple.

**Comment by fairingrey** [comment]
Just a little update, but are you guys expecting something like this for the docs? I've added what a Tide endpoint would look like without the `async` keyword in this commit: https://github.com/fairingrey/tide/commit/3f0bca5f1522a24c00d10e7fe8d96ab7a51fd56e

**Comment by yoshuawuyts** [comment]
@fairingrey fantastic! -- a PR for this would be grand!
