### ISSUE TITLE
Add App::custom or App::with_data

### ISSUE THREAD

**Issue by k-nasa** [rustasync/tide#190]
## Feature Request
```App :: new (())``` looks a bit odd when show example. 
#189 App initialization should be improved as there is this PR too.
I think that I can improve it by introducing App :: custom and App :: with_data.
However, it will change the behavior of the existing App :: new, and the change is likely to increase. What do you think?

## Context

Quote from PR　#189

> This also allows us to more gradually introduce concepts in Tide, allowing us to leave AppData out for an initial introduction, and gradually ease people into using more features.

## Possible Implementation

Introduces App :: with_data and works with existing App :: new. App :: new calls ```App :: with_data (())```.

**Comment by pickfire** [comment]
@k-nasa I understand the need of `App::with_data(())` (actix-web have that too) but I do not know the need for `App::custom()`. What is `App::custom()` for?

**Comment by k-nasa** [comment]
@pickfire  Sorry. I wrote it properly because I could not think of a good name. Please ignore ```App :: custom```.
I considered ```App :: with_data, App :: with_state, App: attach, App :: custom``` etc.

**Comment by secretfader** [comment]
It seems like this issue has a fair bit of overlap with #192. @k-nasa Would you mind commenting there in case the proposed changes don't meet your expectations?

**Comment by secretfader** [comment]
Any objections to closing this issue, @k-nasa? Thanks for the implementation of #192!

**Comment by k-nasa** [comment]
I don't have any objections.
