### ISSUE TITLE
Is it possible to return an HTML response?

### ISSUE THREAD

**Issue by k-nasa** [rustasync/tide#207]
## Question

How do I implement it to return an HTML response?
I checked about response, but "content-type: text / html"
 There is no applicable place in. Also, there is no processing to return HTML in example.
https://github.com/rustasync/tide/blob/7e87e4e0699a3fff4453c8a25d3f8f5fa186fdbb/src/response.rs

However, I think there are many such use cases.

Here is a suggestion, but I think we should implement a response function that returns HTML, and I think it would be nice if there was something to easily change the response header.
And should add an example to return an HTML response

**Comment by yoshuawuyts** [comment]
@k-nasa we've talked about HTML templates before, building a module similar to what we're envisioning for authentication and DB connections.

Right now it's possible to create your own HTML responses with a bit of glue code. I made an example of this late last year: https://github.com/yoshuawuyts/playground-html-rust

Hope this is helpful!

**Comment by k-nasa** [comment]
@yoshuawuyts Thanks! 
I will try to add an example if this [PR](#227 ) is merged.

I wonder what kind of things you are trying to add. Where is the information?

**Comment by k-nasa** [comment]
Closed by #267
