### ISSUE TITLE
Split examples into binaries that are runnable independently

### ISSUE THREAD

**Issue by prasannavl** [rustasync/tide#223]
## Feature Request

- We should make examples runnable individually easily.

## Context

- https://github.com/rustasync/tide/pull/219#pullrequestreview-236996850

## Possible Implementation

- Have each example as separate bin (under `examples/src/bin/`), so that it can be easily run.

**Comment by k-nasa** [comment]
@prasannavl  How about dividing crate one by one?　LIke [actix/example](https://github.com/actix/examples)
Then, I think that the dependency crates of the example becomes obvious.

**Comment by prasannavl** [comment]
@k-nasa - Personally, I like the convenience of switching between files quickly much nicer than having to go through a dir tree for simple examples.

**Comment by yoshuawuyts** [comment]
A bit of a different take here, but I really wish `cargo run --example <name>` would work. I don't think the solution in https://github.com/rustasync/tide/pull/227 is quite good enough, as it still breaks the default way of running examples.

```txt
# expected
$ cargo run --example <example_name>

# proposed in GH-227
$ cargo run -p examples --bin <example_name>
```

I think this might require moving `tide` from a member of the workspace, to the top level under `src/`. Which is similar to [how we do it in Runtime](https://github.com/rustasync/runtime/blob/master/Cargo.toml#L35-L42).
