### ISSUE TITLE
Consider removing or hiding `take_body` fn

### ISSUE THREAD

**Issue by fairingrey** [rustasync/tide#238]
## Feature Removal
This is a suggestion to remove or hide the `take_body` fn from `tide::Context`.

## Context
With the addition of the `request_mut` function, it might be a good idea to consider removing or hiding this function as it's a bit redundant -- one could achieve the same effect by calling `std::mem::replace(cx.request_mut().body_mut(), Body::empty())`.

Although `request_mut` has a much higher surface area, I can't think of many places where one would only want to consume the body outside of extracting forms (which we already provide an interface for through `tide::forms`).

(On that note we should also rename `tide::forms::ExtractForms` to `tide::forms::ContextExt` later...)

## Implementation

We could either achieve this by removing all usage of `take_body` with the aforementioned, or simply just use `pub(crate)` instead.

**Comment by yoshuawuyts** [comment]
@fairingrey I feel we should get our streams story fleshed out + documented completely before we move things out. Ideally I could see us implement `AsyncRead` on `Request` directly, but I feel that might not work out well for us in this case.

Which is to say: I don't feel like I'm currently qualified to judge whether we should remove `take_body`. Probably getting a bit more experience with this would be great.

**Comment by fairingrey** [comment]
That sounds like the better approach for now -- we can always revisit this issue later. The bigger issue at hand should be https://github.com/rustasync/http-service/issues/31. From there we'd be able to better reason about these possible changes.

**Comment by prasannavl** [comment]
@fairingrey I like the idea of sorting out the streams story with https://github.com/rustasync/http-service/issues/31. That being said - I dislike the idea of encouraging the use of `request_mut` - it's nice to have for low level control, but I think the use of that should be discouraged other than specific cases, like the the `compression` module that you just merged - even which I think we probably should find a more refined approach with some abstractions rather than doing `request_mut`.     

Http body (without buffering) is a one time readable. That's the reason `take_body` method exists in the first place - I think that's more obvious in a code base where `take_body` is being used.

**Comment by fairingrey** [comment]
I agree -- most users shouldn't be using `request_mut` anyway, given, as it's only there for particular cases where it's absolutely necessary, such as with `compression` as you've said.

Another remark -- On that note I could refactor it such that middleware context has less overall exposure, but it still requires we somehow have another way to set the body, probably through some `fn set_body(&mut self, body: Body) -> Result<()>` or something like that.

>Http body (without buffering) is a one time readable.

Right, but we do already have other methods for extracting the body in its entirety -- it would only require a change to `body_bytes`.

Ah, also -- sorry I'm not more clear about this. I mean as someone who would likely work directly with the streaming `Body`, they might opt to use something with more low-level control. That said, I think now I'm in support of keeping `take_body` as it stands. But, the bigger concern is if http-service will continue to use `Stream<Item = Result<Bytes, io::Error>` as its underlying body or if we go with something else.

Anyways, sorry to bother you all, but I think we know where we should go with this for now :sweat_smile: Thanks for the replies!
