### ISSUE TITLE
Running under runtime-native silently exits when request is made

### ISSUE THREAD

**Issue by Nemo157** [rustasync/tide#257]
```rust
#![feature(async_await)]

#[runtime::main]
async fn main() -> std::io::Result<()> {
    let mut app = tide::App::new();
    app.at("/").get(async move |_| "Hello, world!");
    app.serve("127.0.0.1:8000").await?;
    Ok(())
}
```

using current `master` of both Tide and Runtime.

Running with `cargo run` starts the server and then sits waiting for a request, once the first request is made it fails to connect and the server silently exits.

Switching to use `runtime_tokio::Tokio` it successfully runs and serves requests.

I would expect if Tide using `http-server-hyper` can't run on `runtime_native` then it would return an error from `serve` when it failed.

**Comment by Nemo157** [comment]
I have tried running `http-service-hyper` directly on `runtime-native` and confirmed it exits with a valid error

```
Error: Custom { kind: Other, error: Error(User(Execute), "tokio::spawn failed (is a tokio runtime running this future?)") }
```

checking the code there is a todo about this https://github.com/rustasync/tide/blob/8b667fed05b2cb306d00835188f5a4427431b713/tide-core/src/app.rs#L260-L263

**Comment by fairingrey** [comment]
What do you suppose would be a good error message for this? [`std::io::ErrorKind`](https://doc.rust-lang.org/std/io/enum.ErrorKind.html) doesn't quite have anything that fits this particular case... Should `serve` return a different type of result with the `hyper::Error` type?
