### ISSUE TITLE
Middleware for compression

### ISSUE THREAD

**Issue by aturon** [rustasync/tide#26]
A good test of the middleware system would be to implement gzip compression as middleware (transforming the body and headers on the way in/out).

**Comment by yoshuawuyts** [comment]
This would tie in nicely with https://github.com/rust-lang-nursery/wg-net/issues/52

**Comment by fairingrey** [comment]
I took up this issue up roughly two weeks ago through https://github.com/rustasync/tide/pull/194 and progress is almost finished. There are some things I want to wrap up before I submit it for review.
