### ISSUE TITLE
Failed to compile tide

### ISSUE THREAD

**Issue by zarnipyo** [rustasync/tide#284]
## Question
How to try out tide?

Relatively new to rust community.

I tried out with latest nightly rust and tide from the master github repo.
I got the following compiling error when trying to run helloworld example.

error[E0437]: type `ResponseFuture` is not a member of trait `HttpService`
error[E0220]: associated type `ResponseFuture` not found for `Self`

Any help would be greatly appreciated.

**Comment by zarnipyo** [comment]
The error goes away with version 0.2.0. I'll close the issue here. Sorry about that.

**Comment by yoshuawuyts** [comment]
@zarnipyo no worries, happy you were able to figure it out!
