### ISSUE TITLE
Why get_cookie take a mutable reference ?

### ISSUE THREAD

**Issue by langbamit** [rustasync/tide#316]
## Question
https://github.com/rustasync/tide/blob/c41ed8407da13bd2db77af9357befb0b334f344a/tide-cookies/src/data.rs#L32

My English is bad. Sorry for this
## Additional context

I want extract authentication token from header or cookie and I suprise when get_cookie take a `&mut self` instead of `&self` like `headers()` function

**Comment by kamyuentse** [comment]
Change to `get_cookie(&self, name: &str)` is reasonable. Indeed, `set_cookie` and `remove_cookie` are not require `&mut self` for current implementation.

**Comment by secretfader** [comment]
Closed by #317.
