### ISSUE TITLE
Want to output logs without installing env_logger

### ISSUE THREAD

**Issue by k-nasa** [rustasync/tide#323]
## Question
I want to output logs without installing env_logger

Currently, log crate should be required separately from tide.
Is it possible to complete it with only tide?

It is good that users can output log with less crate

**Comment by yoshuawuyts** [comment]
No yeah, the log crate definitely requires its own frontend. I recommend using https://docs.rs/femme/1.2.0/femme/ for that. Though if you'd like to implement a more minimal version, you can always implement a variation on https://github.com/lrlna/femme/pull/4.

Hope this is helpful!

**Comment by k-nasa** [comment]
thx!
