### ISSUE TITLE
Strip the result body when creating default HEAD responses

### ISSUE THREAD

**Issue by aturon** [rustasync/tide#45]
If you don't specify a `HEAD` behavior but you do provide `GET`, Tide will automatically use the `GET` behavior. But it retains the body, which should be stripped.

**Comment by tzilist** [comment]
@aturon did a little diggin into this, not sure if I am reading this right either, but it seems like hyper handles this for us. In the current code on master here are some example responses from curl
I'm running the `named_path` example:
```bash
url --get  --url http://127.0.0.1:8000/add_two/2   --header 'content-type: application/json' -v
```
Returns
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> GET /add_two/2 HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
> Accept: */*
> Referer:
> content-type: application/json
>
< HTTP/1.1 200 OK
< content-type: text/plain
< content-length: 15
< date: Mon, 19 Nov 2018 04:53:55 GMT
<
* Connection #0 to host 127.0.0.1 left intact
2 plus two is 4
```

and the head request:

```bash
curl --head  --url http://127.0.0.1:8000/add_two/2   --header 'content-type: application/json' -v
```
returns
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> HEAD /add_two/2 HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
> Accept: */*
> Referer:
> content-type: application/json
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< content-type: text/plain
content-type: text/plain
< content-length: 15
content-length: 15
< date: Mon, 19 Nov 2018 04:53:33 GMT
date: Mon, 19 Nov 2018 04:53:33 GMT

<
* Connection #0 to host 127.0.0.1 left intact
```

Perhaps I am missing something though. Thoughts?

**Comment by DeltaManiac** [comment]
@tzilist 

I had observed the same behavior while testing #31. 
Guess i missed something too :)

**Comment by aturon** [comment]
That's very interesting. I haven't been able to track down where this is happening in Hyper...

**Comment by aturon** [comment]
@seanmonstar maybe you can provide a quick answer: does Hyper have built-in treatment for `HEAD` requests and if so, what is it?

**Comment by seanmonstar** [comment]
hyper will try to prevent illegal HTTP semantics, like sending a body in response to `HEAD` requests, or in `204`/`304` status codes.

It may still be useful to recognize a `HEAD` request is different from a `GET` in cases where *preparing* the body may have been expensive.

**Comment by tzilist** [comment]
@aturon if this is the case, should we just write a test case to ensure that `HEAD` requests always strip the body? We can just rely on hyper to handle this and the test case to make sure it doesn't break.

**Comment by aturon** [comment]
@tzilist Yep, that seems reasonable for now!  I'd also suggest adding a comment to make clear that's  what we're doing.

**Comment by fairingrey** [comment]
I attempted to write a test for this given the mock service provided through `http_service_mock` but I'm running into something strange... There's more details in my PR: https://github.com/rustasync/tide/pull/179

**Comment by WSeegers** [comment]
Has this issue been fully resolved?

**Comment by yoshuawuyts** [comment]
@WSeegers I think it may have been in https://github.com/rustasync/tide/pull/179. Going to go ahead and close this!
