### ISSUE TITLE
Factor out low-level http server concerns

### ISSUE THREAD

**Issue by aturon** [rustasync/tide#53]
Right now, Tide defines several general-purpose data types (like `Body`) and mucks around with futures-compat layers for using Hyper. These things aren't Tide-specific, and should be factored out as a separate crate that layers on top of Hyper, so that others can use them more easily.

**Comment by aturon** [comment]
FYI: I'm working on this issue.

**Comment by zmlzm** [comment]
@aturon there is also a new [Actix-http](https://github.com/fafhrd91/actix-http) http library, I find.

**Comment by aturon** [comment]
The refactor in https://github.com/rust-net-web/tide/pull/139 took a major step in this direction, but we'll ultimately want to move out the shim code into its own crate and make Tide truly modular in this respect.

**Comment by luover** [comment]
There is also [actix-http](https://github.com/actix/actix-http), It support HTTP1/2 Server/Client and Websocket Server/Client.

**Comment by aturon** [comment]
This is done as of #140!
