### ISSUE TITLE
Separating app-global data and request-local data

### ISSUE THREAD

**Issue by tirr-c** [rustasync/tide#56]
Currently there is `Data` we can give to `App`. It is owned by the App and looks like an app-global state, but acts like a request-local state. It is cloned on *every* request. I think this can lead to confusion because some states persist between requests (e.g. `Arc<Mutex<T>>`) and some do not.

My proposal is to:

* Make middleware get an immutable reference to App data. This way it becomes clear that the data is shared in the app and across threads.
* Use `req.extensions()` or some other typemap for request-local data from middleware. A new typemap would be better because data would be easily extracted (I suppose).

Maybe I'm missing something, so feel free to comment!

**Comment by aturon** [comment]
Lemme clarify a bit where the current design came from.

Unfortunately, right now with `async fn` there are some compiler limitations around borrowing, which prevent us from easily passing in `&Data` to the endpoint:

```rust
#![feature(async_await, futures_api)]

use std::future::Future;

async fn take_ref(data: &Vec<u8>) {}

trait TakeRef {
    type Fut: Future<Output = ()>;
    fn call(&self, data: &Vec<u8>) -> Self::Fut;
}

impl<F, Fut> TakeRef for F
where
    F: Fn(&Vec<u8>) -> Fut,
    Fut: Future<Output = ()>,
{
    type Fut = Fut;
    fn call(&self, data: &Vec<u8>) -> Self::Fut {
        (self)(data)
    }
}

fn try_it<T: TakeRef>(t: T) {}

fn main() {
    try_it(take_ref);
}
```

gives

```
error[E0271]: type mismatch resolving `for<'r> <for<'s> fn(&'s std::vec::Vec<u8>) -> impl std::future::Future {take_ref} as std::ops::FnOnce<(&'r std::vec::Vec<u8>,)>>::Output == _`
  --> src/main.rs:26:5
   |
26 |     try_it(take_ref);
   |     ^^^^^^ expected bound lifetime parameter, found concrete lifetime
```

Eventually this compiler limitation will be fixed, but we have to work around it for now.

So instead, the intent was that app data would be a cloneable "handle" to the data -- most likely an `Arc` -- and we'd pass in an "owned" handle to each endpoint. But it is still meant to represent app-global data.

However, I think I now see a way that we can pass in a reference to the global data *everywhere*, including the endpoint. I'll experiment with that and link back here with the results.

----

Regarding `extensions`, that is indeed what I had in mind for request-local data coming from middleware -- at least for cases where that data should be available to other middleware or the endpoint.

**Comment by aturon** [comment]
OK, I tried out the experiment I had in mind (a way to thread references to `Data` throughout), but it hit a snag that hyper requires the root server code to be `'static`. So I think we just have to stick with `Arc` and cloning for now, until the compiler limitation is fixed.

**Comment by aturon** [comment]
I believe this story is much more clear as of #156, closing for now!

**Comment by kjvalencik** [comment]
@aturon Is your comment from https://github.com/rustasync/tide/issues/56#issuecomment-441431338 still a limitation of the compiler? I'm trying to accomplish something similar but, have had difficulty finding a tracking issue or anything related. Thanks!

**Comment by yoshuawuyts** [comment]
@kjvalencik I believe similar restrictions still apply.

**Comment by kjvalencik** [comment]
Thanks @yoshuawuyts. Is https://github.com/rustasync/team/issues/19 the related issue?
