### ISSUE TITLE
"Catch-all" endpoint

### ISSUE THREAD

**Issue by tirr-c** [rustasync/tide#62]
Sometimes, especially with static file serving, it's necessary to route *all* subpaths to one endpoint. For example, if `/static` is that kind of "catch-all" endpoint, paths like `/static/foo.txt` and `/static/images/bar.jpg` will be routed to that endpoint.

We can't make a catch-all endpoint with current router API, so we need to implement one.

**Comment by bIgBV** [comment]
An idea that comes to mind is using a setup similar [to the one in Django](https://docs.djangoproject.com/en/2.1/howto/static-files/). We can have a `STATIC_URL` set up through configuration. This I think would be a relatively easy way to add a catch all endpoint.

Of course, the issue would be that depending on the way config is done, you won't be able to change the URL programatically.

**Comment by aturon** [comment]
This currently works via `/static/:path*`.
