### ISSUE TITLE
Proposal: Rename `App`

### ISSUE THREAD

**Issue by skade** [rustasync/tide#75]
Currently, the `App` object is a mix between a builder (it's the interface to globally manipulating the router) and can be turned `into_server` and a global entry point into building something that can be called into. I'm not sure if `App` is a good name for it.

Mainly, it collides with a frequent usage of `App` in other frameworks, for example, Django uses `App` four a _mountable_ subapp (basically a collection of endpoints). https://docs.djangoproject.com/en/2.1/ref/settings/#installed-apps

**Comment by aturon** [comment]
Related: do we want to do something more sophisticated with the current "app" concept, like mountable sub-apps and/or the ability to `map` functions over the application state as you descend the router?

**Comment by aturon** [comment]
With the #156 revamp, we *do* intend to allow `App`s to be nested; that desire is tracked in https://github.com/rustasync/tide/issues/160. I'm closing this issue for the time being.
